services:
  backend:
    profiles: ["dev"]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # ← 변수명이 app일 때
    environment:
      - GOOGLE_API_KEY=AIzaSyCPbFbFjbAeAbFWkCIeLTnOPy8DQ4YxAvc
      - PYTHONPATH=/app
      - ENV=dev
    volumes:
      - ./src:/app      # 로컬 ./src -> 컨테이너 /app (그 아래에 app/, services/ 등 포함)
    ports:
      - "8000:8000"
    restart: unless-stopped

  worker:
    profiles: ["dev"]
    # Celery 엔트리 경로도 동일 규칙(예: app.core.celery_app:celery)
    command: bash -lc "celery -A app.core.celery_app worker -Q validation -l INFO"
    environment:
      - GOOGLE_API_KEY=AIzaSyCPbFbFjbAeAbFWkCIeLTnOPy8DQ4YxAvc
      - PYTHONPATH=/app
      - ENV=dev
      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg://xistoh:mk685700@34.64.87.169:5432/screwed}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://redis:6379/0}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
    volumes:
      - ./src:/app
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    profiles: ["dev"]
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  flower:
    profiles: ["dev"]
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://redis:6379/0}
    ports:
      - "5555:5555"
    depends_on:
      - redis
    restart: unless-stopped